/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import EstructurasAuxiliares.ListaArista;
import EstructurasAuxiliares.ListaNodoAlmacen;
import EstructurasAuxiliares.ListaProducto;
import Logico.Amazon;
import Logico.Arista;
import Logico.NodoAlmacen;
import Logico.Producto;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alessandro
 */
public class CargarArchivo extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel();
    ListaNodoAlmacen almacenes;
    
    public CargarArchivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        String[] cabeceraTabla = new String[]{"Almacen", "Conecta con", "Distancia", "Productos", "Stock"};
        modelo.setColumnIdentifiers(cabeceraTabla);
        tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtFieldArchivo = new javax.swing.JTextField();
        guardarArchivo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 169, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 860, 80));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 590, 240));

        txtFieldArchivo.setEditable(false);
        txtFieldArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 40));

        guardarArchivo.setBackground(new java.awt.Color(0, 153, 51));
        guardarArchivo.setText("Guardar Archivo");
        guardarArchivo.setEnabled(false);
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, 40));

        jButton4.setText("Cargar Archivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 40));

        lblTitulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Contenido del Archivo");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 460, -1));

        jLabel1.setText(" Y visualizarlo en la tabla de la izquierda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 220, 20));

        jLabel2.setText("perderás al cerrar el programa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, 220, 20));

        jLabel3.setText("Presiona el botón para cargar un poducto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 20));

        jLabel4.setText("Si no guardas los datos en el sistema los");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 20));

        lblSeparador.setBackground(new java.awt.Color(51, 51, 51));
        lblSeparador.setOpaque(true);
        jPanel1.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 20, 2, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldArchivoActionPerformed

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        Amazon.getInstance().actualizarRepositorio(almacenes);
        guardarArchivo.setEnabled(false);
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        File archivo;
        JFileChooser seleccionarFile = new JFileChooser();
        seleccionarFile.showOpenDialog(null);
        archivo = seleccionarFile.getSelectedFile();
        almacenes = Amazon.getInstance().cargarDatos(archivo.getAbsolutePath());
        txtFieldArchivo.setText(archivo.getAbsolutePath());
        guardarArchivo.setEnabled(true);
        crearTabla(almacenes);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CargarArchivo dialog = new CargarArchivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtFieldArchivo;
    // End of variables declaration//GEN-END:variables

    private void crearTabla(ListaNodoAlmacen almacenes) {
        
        String[] columnas = new String[modelo.getColumnCount()];
        modelo.setRowCount(0);
        int size;        
        for (NodoAlmacen almacen: almacenes.getAlmacenes()) {
            if (almacen.getListaProducto().getSize() > almacen.getListaArista().getSize()) {
                size = almacen.getListaProducto().getSize();
            }else{
                size = almacen.getListaArista().getSize();
            }
            for (int i = 0; i < size; i++) {
                if (i >= almacen.getListaArista().getSize() && i < almacen.getListaProducto().getSize()) {
                    modelo.addRow(new Object[]{almacen.getNombre(), "", "", almacen.getListaProducto().getProductos()[i].getNombre(), almacen.getListaProducto().getProductos()[i].getStock()});
                }else if (i < almacen.getListaArista().getSize() && i >= almacen.getListaProducto().getSize()) {
                    modelo.addRow(new Object[]{almacen.getNombre(), almacen.getListaArista().getAristas()[i].getNodoDestino().getNombre(), almacen.getListaArista().getAristas()[i].getDistancia(), "",""});
                }else{
                    System.out.println("Size en es momento: " + i);
                    modelo.addRow(new Object[]{almacen.getNombre(), almacen.getListaArista().getAristas()[i].getNodoDestino().getNombre(), almacen.getListaArista().getAristas()[i].getDistancia(), almacen.getListaProducto().getProductos()[i].getNombre(), almacen.getListaProducto().getProductos()[i].getStock()});
                }
            }
        }
    }
}
