/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import EstructurasAuxiliares.ListaNodoAlmacen;
import Logico.Amazon;
import Logico.NodoAlmacen;
import javax.swing.table.DefaultTableModel;
import java.awt.Frame;

/**
 *
 * @author Alessandro
 */
public class GestionAlmacen extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel();
    ListaNodoAlmacen almacenes;
    
    public GestionAlmacen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        String[] cabeceraTabla = new String[]{"Almacen", "Conecta con", "Distancia", "Productos", "Stock"};
        modelo.setColumnIdentifiers(cabeceraTabla);
        tabla.setModel(modelo);
        crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        guardarArchivo = new javax.swing.JButton();
        crearNuevaRuta = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        crearNuevoProducto = new javax.swing.JButton();
        crearAlmacen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 169, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 860, 80));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 590, 240));

        guardarArchivo.setBackground(new java.awt.Color(0, 153, 51));
        guardarArchivo.setText("Guardar Archivo");
        guardarArchivo.setEnabled(false);
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 50));

        crearNuevaRuta.setText("Crear nuevas rutas");
        crearNuevaRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevaRutaActionPerformed(evt);
            }
        });
        jPanel1.add(crearNuevaRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 40));

        lblTitulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Almacenes");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 460, -1));

        jLabel2.setText("Puede guardar lso cambios aquí o en el ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 20));

        jLabel4.setText("Menu principal presionando \"Actualizar\"");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 20));

        lblSeparador.setBackground(new java.awt.Color(51, 51, 51));
        lblSeparador.setOpaque(true);
        jPanel1.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 20, 2, 280));

        crearNuevoProducto.setText("Stock Productos");
        crearNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(crearNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 40));

        crearAlmacen.setText("Crear un Almacen");
        crearAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(crearAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        Amazon.getInstance().actualizarRepositorioSobrescribir();
        guardarArchivo.setEnabled(false);
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void crearNuevaRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevaRutaActionPerformed
        CrearRuta crearRuta = new CrearRuta(new Frame(), true);
        crearRuta.setVisible(true);
        crearTabla();
        guardarArchivo.setEnabled(true);
    }//GEN-LAST:event_crearNuevaRutaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void crearNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevoProductoActionPerformed
        ProductoStock productoStock = new ProductoStock(new Frame(), true);
        productoStock.setVisible(true);
        crearTabla();
        guardarArchivo.setEnabled(true);
    }//GEN-LAST:event_crearNuevoProductoActionPerformed

    private void crearAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAlmacenActionPerformed
        CrearAlmacen crearAlmacen = new CrearAlmacen(new Frame(), true);
        crearAlmacen.setVisible(true);
        crearTabla();
        guardarArchivo.setEnabled(true);
    }//GEN-LAST:event_crearAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionAlmacen dialog = new GestionAlmacen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton crearAlmacen;
    private javax.swing.JButton crearNuevaRuta;
    private javax.swing.JButton crearNuevoProducto;
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void crearTabla() {
        
        String[] columnas = new String[modelo.getColumnCount()];
        modelo.setRowCount(0);
        int size;        
        for (NodoAlmacen almacen: Amazon.getInstance().getListaMisAlmacenes().getAlmacenes()) {
            if (almacen.getListaProducto().getSize() > almacen.getListaArista().getSize()) {
                size = almacen.getListaProducto().getSize();
            }else{
                size = almacen.getListaArista().getSize();
            }
            for (int i = 0; i < size; i++) {
                if (i >= almacen.getListaArista().getSize() && i < almacen.getListaProducto().getSize()) {
                    modelo.addRow(new Object[]{almacen.getNombre(), "", "", almacen.getListaProducto().getProductos()[i].getNombre(), almacen.getListaProducto().getProductos()[i].getStock()});
                }else if (i < almacen.getListaArista().getSize() && i >= almacen.getListaProducto().getSize()) {
                    modelo.addRow(new Object[]{almacen.getNombre(), almacen.getListaArista().getAristas()[i].getNodoDestino().getNombre(), almacen.getListaArista().getAristas()[i].getDistancia(), "",""});
                }else{
                    modelo.addRow(new Object[]{almacen.getNombre(), almacen.getListaArista().getAristas()[i].getNodoDestino().getNombre(), almacen.getListaArista().getAristas()[i].getDistancia(), almacen.getListaProducto().getProductos()[i].getNombre(), almacen.getListaProducto().getProductos()[i].getStock()});
                }
            }
        }
    }
}
