/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Logico.Amazon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        //Esta parte lo que hace es cargar en memoria los datos contenidos en el fichero.
        Amazon.getInstance().cargarFichero("src/Archivos/Amazon.txt");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        lblAmazon = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblFondoMenu = new javax.swing.JLabel();
        lblGestionAlmacenes = new javax.swing.JLabel();
        lblReporte = new javax.swing.JLabel();
        lblActualizarArchivo = new javax.swing.JLabel();
        lblRealizarPedido = new javax.swing.JLabel();
        lblArchivo = new javax.swing.JLabel();
        lblMostrarGrafo = new javax.swing.JLabel();
        btnRealizarPedido = new javax.swing.JButton();
        btnCargarArchivo = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnGestionAlmacenes = new javax.swing.JButton();
        btnMostrarGrafo = new javax.swing.JButton();
        btnActualizarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(153, 153, 153));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 38)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Sistema de Inventario");
        panelSuperior.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 460, -1));

        lblSeparador.setBackground(new java.awt.Color(51, 51, 51));
        lblSeparador.setOpaque(true);
        panelSuperior.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 2, 100));

        lblAutores.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblAutores.setForeground(new java.awt.Color(255, 255, 255));
        lblAutores.setText("Alessandro Flammia | Diego Ramos");
        panelSuperior.add(lblAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 330, -1));

        lblAmazon.setBackground(new java.awt.Color(51, 51, 51));
        lblAmazon.setFont(new java.awt.Font("Arial Black", 0, 60)); // NOI18N
        lblAmazon.setForeground(new java.awt.Color(51, 51, 51));
        lblAmazon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAmazon.setText("Amazon");
        panelSuperior.add(lblAmazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 270, 80));

        panelPrincipal.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 120));

        lblMenu.setBackground(new java.awt.Color(51, 51, 51));
        lblMenu.setFont(new java.awt.Font("Arial Black", 0, 40)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(204, 204, 204));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMenu.setText("Menu");
        panelPrincipal.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 280, 60));

        lblFondoMenu.setBackground(new java.awt.Color(32, 32, 32));
        lblFondoMenu.setFont(new java.awt.Font("Arial Black", 0, 38)); // NOI18N
        lblFondoMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFondoMenu.setOpaque(true);
        panelPrincipal.add(lblFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 60));

        lblGestionAlmacenes.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblGestionAlmacenes.setForeground(new java.awt.Color(51, 51, 51));
        lblGestionAlmacenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionAlmacenes.setText("Gestion Almacenes");
        panelPrincipal.add(lblGestionAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 170, 30));

        lblReporte.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblReporte.setForeground(new java.awt.Color(51, 51, 51));
        lblReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporte.setText("Reporte");
        panelPrincipal.add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 170, 30));

        lblActualizarArchivo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblActualizarArchivo.setForeground(new java.awt.Color(51, 51, 51));
        lblActualizarArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizarArchivo.setText("Actualizar archivo");
        panelPrincipal.add(lblActualizarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 150, 30));

        lblRealizarPedido.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblRealizarPedido.setForeground(new java.awt.Color(51, 51, 51));
        lblRealizarPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRealizarPedido.setText("Realizar Pedido");
        panelPrincipal.add(lblRealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 170, 30));

        lblArchivo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblArchivo.setForeground(new java.awt.Color(51, 51, 51));
        lblArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArchivo.setText("Cargar Archivo");
        panelPrincipal.add(lblArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 120, 30));

        lblMostrarGrafo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblMostrarGrafo.setForeground(new java.awt.Color(51, 51, 51));
        lblMostrarGrafo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarGrafo.setText("Mostrar Grafo");
        panelPrincipal.add(lblMostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 120, 30));

        btnRealizarPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnRealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 170, 90));

        btnCargarArchivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnCargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 170, 90));

        btnReporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 170, 90));

        btnGestionAlmacenes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGestionAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionAlmacenesActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnGestionAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 170, 90));

        btnMostrarGrafo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGrafoActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnMostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 170, 90));

        btnActualizarArchivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarArchivoActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnActualizarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 170, 90));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        Reporte reporte = new Reporte(this, true);
        reporte.setVisible(true);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        CargarArchivo archivo = new CargarArchivo(this, true);
        archivo.setVisible(true);
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        RealizarPedido realizarPedido = new RealizarPedido(this, true);
        realizarPedido.setVisible(true);
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void btnGestionAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAlmacenesActionPerformed
        GestionAlmacen gestionAlmacen = new GestionAlmacen(this, true);
        gestionAlmacen.setVisible(true);
    }//GEN-LAST:event_btnGestionAlmacenesActionPerformed

    private void btnMostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarGrafoActionPerformed

    private void btnActualizarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarArchivoActionPerformed
        Amazon.getInstance().actualizarRepositorioSobrescribir();
        JOptionPane.showMessageDialog(null, "El repositorio fue actualizado correctamente");
    }//GEN-LAST:event_btnActualizarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarArchivo;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnGestionAlmacenes;
    private javax.swing.JButton btnMostrarGrafo;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel lblActualizarArchivo;
    private javax.swing.JLabel lblAmazon;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblFondoMenu;
    private javax.swing.JLabel lblGestionAlmacenes;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMostrarGrafo;
    private javax.swing.JLabel lblRealizarPedido;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
