/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import EstructurasAuxiliares.ListaProducto;
import Logico.Amazon;
import Logico.NodoAlmacen;
import Logico.Producto;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Alessandro
 */


public class ProductoStock extends javax.swing.JDialog {    
    ListaProducto listaProducto = new ListaProducto();
    DefaultComboBoxModel<String> modeloCbx = new DefaultComboBoxModel<>();
    
    public ProductoStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cargarOpcionesCbx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        lblTitulo3 = new javax.swing.JLabel();
        almacenSeleccionar = new javax.swing.JComboBox<>();
        lblTitulo4 = new javax.swing.JLabel();
        lblTitulo5 = new javax.swing.JLabel();
        lblTitulo6 = new javax.swing.JLabel();
        lblTitulo7 = new javax.swing.JLabel();
        lblTitulo8 = new javax.swing.JLabel();
        nombreAgregar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        cantidadAgregar = new javax.swing.JSpinner();
        lblTitulo9 = new javax.swing.JLabel();
        nombreAumentar = new javax.swing.JTextField();
        lblTitulo10 = new javax.swing.JLabel();
        cantidadAumentar = new javax.swing.JSpinner();
        agregar = new javax.swing.JButton();
        lblSeparador = new javax.swing.JLabel();
        aumentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Cerrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 570, 60));

        lblTitulo3.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo3.setText("Seleccionar Almacen");
        jPanel1.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, -1));

        almacenSeleccionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        almacenSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(almacenSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 30));

        lblTitulo4.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo4.setText("> Productos");
        jPanel1.add(lblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, -1));

        lblTitulo5.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo5.setText("Cantidad:");
        jPanel1.add(lblTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        lblTitulo6.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo6.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo6.setText("> Aumentar Stock");
        jPanel1.add(lblTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 230, -1));

        lblTitulo7.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo7.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo7.setText("> Agregar Producto");
        jPanel1.add(lblTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, -1));

        lblTitulo8.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo8.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo8.setText("Nombre:");
        jPanel1.add(lblTitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, -1));
        jPanel1.add(nombreAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 30));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 70, 30));
        jPanel1.add(cantidadAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 30));

        lblTitulo9.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo9.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo9.setText("Nombre:");
        jPanel1.add(lblTitulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 80, -1));
        jPanel1.add(nombreAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 80, 30));

        lblTitulo10.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitulo10.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo10.setText("Cantidad:");
        jPanel1.add(lblTitulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 90, -1));
        jPanel1.add(cantidadAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 160, 30));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, 30));

        lblSeparador.setBackground(new java.awt.Color(51, 51, 51));
        lblSeparador.setOpaque(true);
        jPanel1.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 85, 2, 170));

        aumentar.setText("Aumentar");
        aumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarActionPerformed(evt);
            }
        });
        jPanel1.add(aumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void almacenSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenSeleccionarActionPerformed
    }//GEN-LAST:event_almacenSeleccionarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        NodoAlmacen almacen = Amazon.getInstance().getAlmacen(almacenSeleccionar.getSelectedItem().toString());
        Producto producto = Amazon.getInstance().buscarProducto(nombreAumentar.getText(), almacen.getNombre());
        if (producto == null) {
            JOptionPane.showMessageDialog(null, "Este producto no existe dentro del almacen " +  almacen.getNombre());
        }else{
            JOptionPane.showMessageDialog(null, "Producto encontrado con exito");
            SpinnerNumberModel modelo = new SpinnerNumberModel();
            cantidadAumentar.setModel(modelo);
            modelo.setValue(producto.getStock());
            modelo.setMinimum(producto.getStock());
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        NodoAlmacen almacen = Amazon.getInstance().getAlmacen(almacenSeleccionar.getSelectedItem().toString());
        Producto producto = new Producto(nombreAgregar.getText(),Integer.parseInt(cantidadAgregar.getValue().toString()), almacen);
        if (verificarNombre(producto.getNombre()) == false) {
            almacen.getListaProducto().add(producto);
            JOptionPane.showMessageDialog(null, "Producto agregado correctamente");
        }else{
            JOptionPane.showMessageDialog(null, "El producto ya existe en este Almacen");
        }
        
    }//GEN-LAST:event_agregarActionPerformed

    private void aumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarActionPerformed
        NodoAlmacen almacen = Amazon.getInstance().getAlmacen(almacenSeleccionar.getSelectedItem().toString());
        Producto producto = Amazon.getInstance().buscarProducto(nombreAumentar.getText(), almacen.getNombre());
        producto.setStock(Integer.parseInt(cantidadAumentar.getValue().toString()));
        JOptionPane.showMessageDialog(null, "Stock Aumentado Correctamente");
    }//GEN-LAST:event_aumentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoStock dialog = new ProductoStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> almacenSeleccionar;
    private javax.swing.JButton aumentar;
    private javax.swing.JButton buscar;
    private javax.swing.JSpinner cantidadAgregar;
    private javax.swing.JSpinner cantidadAumentar;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTitulo10;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JLabel lblTitulo7;
    private javax.swing.JLabel lblTitulo8;
    private javax.swing.JLabel lblTitulo9;
    private javax.swing.JTextField nombreAgregar;
    private javax.swing.JTextField nombreAumentar;
    // End of variables declaration//GEN-END:variables


    private void cargarOpcionesCbx() {
        modeloCbx.removeAllElements();
        almacenSeleccionar.setModel(modeloCbx);
        for (NodoAlmacen almacen : Amazon.getInstance().getListaMisAlmacenes().getAlmacenes()) {
            modeloCbx.addElement(almacen.getNombre());
        }
    }
    
    private boolean verificarNombre(String nombre) {
        NodoAlmacen almacen = Amazon.getInstance().getAlmacen(almacenSeleccionar.getSelectedItem().toString());
        for (Producto producto : almacen.getListaProducto().getProductos()) {
            if (producto != null) {
                if (producto.getNombre().equalsIgnoreCase(nombre)) {
                    return true;
                }
            }
        }
        return false;
    }
}
